Revert "devel: dont'require params when using defaults, use "aggregated" unset()"
This reverts commit 2fe64ae7d87deb2fd2b3930ecd3ef25f893a41f0.

Reason: causes 'PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function LMS::GetNetNodeList()'